services:
  bot-service:
    container_name: bot-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - logs:/usr/app/logs
      - data:/usr/app/data
      - db:/usr/app/db
    entrypoint: ["python", "bot.py"]

  bot-worker-service:
    container_name: bot-worker-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - logs:/usr/app/logs
      - data:/usr/app/data
      - db:/usr/app/db
    entrypoint: ["python", "bot_worker.py"]

  api-service:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - logs:/usr/app/logs
      - data:/usr/app/data
      - db:/usr/app/db
    entrypoint: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  web-service:
    container_name: web-service
    build:
      context: ../th042025-client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../th042025-client/dist/th042025-client/browser:/usr/share/nginx/html

volumes:
  logs:
  data:
  db:
